[host]
base_url = "https://www.backroomswiki.ru"
login_url = "/-/login"
files_url = "/local--files/"
api_articles = "/api/articles/"

# path pages to store fonts (css) and (woff2) files
css_fonts_url = "/system:fonts"
woff2_fonts_url = "/system:fonts-base"

[images]
components = ["component:level-class", "component:image-block", "component:forum-block",
    "component:image-block-spoiler", "component:photocard-block-base", "component:hinc",
    "component:level-card",
    "image", "=image", "<image", ">image", "f>image", "f<image"]
