[host]
base_url = "https://www.backroomswiki.ru"
login_url = "/-/login"
files_url = "/local--files/"
api_articles = "/api/articles/"
api_files = "/api/files/"


# path pages to store fonts (css) and (woff2) files
# NOT START WITH /
css_fonts_url = "system:fonts"
woff2_fonts_url = "system:fonts-base"

[images]
components = ["component:level-class", "component:image-block", "component:forum-block",
    "component:image-block-spoiler", "component:photocard-block-base", "component:hinc",
    "component:level-card", "component:image-block-spoiler", "component:level-card",
    "image", "=image", "<image", ">image", "f>image", "f<image"]

[replace]
in = ["backrooms-wiki.ru", "wdfiles.com", "ru-backrooms-wiki", "backroomswiki.ru"]

[patch]
"backrooms-wiki.ru" = "https://www.backroomswiki.ru"
"en.backrooms-wiki.ru" = "http://backrooms-wiki.wikidot.com"

[users]
wd_file = ""