[requests]
user_agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"
session_file = "config/.session.json"

[base]
current_site = "backroomswiki.ru"

# Logging settings
[logging]
file_path = 'logs/cli.log'
level = "INFO"
format = "<green>{time:YYYY-MM-DD HH:mm:ss}</green> [<bold>{level.icon}<level>{level}</level></bold>] <magenta>{name}</magenta> - {message}"
rotation = "1 day"
enqueue = "True"
colorize = "True"
